
service: serverless-perhap

provider:
  name: aws
  runtime: python2.7
  region: us-west-2
  environment:
    PerhapEvents: Perhap-Events
    PerhapDomains: Perhap-Domains
    PerhapEntities: Perhap-Entities
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ["arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Perhap-Events", "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Perhap-Events/*", "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Perhap-Domains", "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/Perhap-Entities"]

functions:
  get-domain:
    handler: two-parts-handler.domain
    events:
      - http:
          method: get
          path: events/{realm}/{domain}
  put-bulk:
    handler: post-handler.bulk_post
    events:
      - http:
          method: post
          path: events/{realm}/bulk
  get-events:
    handler: three-parts-handler.get_events
    events:
      - http:
          method: get
          path: events/{realm}/{domain}/{entity}
  new-event:
    handler: post-handler.new_event
    events:
      - http:
          method: post
          path: events/{realm}/{domain}/{entity}/{event-type}/{event-id}


resources:
  Resources:
    DynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Realm"
            AttributeType: "S"
          -
            AttributeName: "RangeId"
            AttributeType: "S"
          -
            AttributeName: "EventId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Realm"
            KeyType: "HASH"
          -
            AttributeName: "RangeId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "10"
          WriteCapacityUnits: "50"
        LocalSecondaryIndexes:
        -
          IndexName: "event-id"
          KeySchema:
            -
              AttributeName: "Realm"
              KeyType: "HASH"
            -
              AttributeName: "EventId"
              KeyType: "RANGE"
          Projection:
            ProjectionType: ALL
        TableName: ${self:provider.environment.PerhapEvents}
    DomainDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "Realm"
            AttributeType: "S"
          -
            AttributeName: "PerhapDomain"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "Realm"
            KeyType: "HASH"
          -
            AttributeName: "PerhapDomain"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "10"
          WriteCapacityUnits: "50"
        TableName: ${self:provider.environment.PerhapDomains}
    EntityDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "PerhapDomain"
            AttributeType: "S"
          -
            AttributeName: "Entity"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "PerhapDomain"
            KeyType: "HASH"
          -
            AttributeName: "Entity"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: "10"
          WriteCapacityUnits: "50"
        TableName: ${self:provider.environment.PerhapEntities}
    # Kinesis:
    #   Type: "AWS::Kinesis::Stream"
    #   Properties:
    #     Name: Perhap-Kinesis
    #     ShardCount: 1
